spring.application.name=college
#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/collegedb
spring.datasource.username=postgres
spring.datasource.password=Google@12345

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql